default_config:

logger:
  default: warning
  logs:
    custom_components.meross_lan: debug

# If you need to debug uncommment the line below (doc: https://www.home-assistant.io/integrations/debugpy/)
debugpy:
